# Generated by Django 2.2.7 on 2019-11-07 12:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Planet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Имя')),
            ],
            options={
                'verbose_name': 'Платена',
                'verbose_name_plural': 'Планета',
                'db_table': 'Планета',
            },
        ),
        migrations.CreateModel(
            name='Sith',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('planet', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sith_planet', to='sith.Planet', verbose_name='Планета обучения')),
            ],
            options={
                'verbose_name': 'Ситх',
                'verbose_name_plural': 'Ситхи',
                'db_table': 'Ситхи',
                'ordering': ['planet'],
            },
        ),
        migrations.CreateModel(
            name='Recruit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Имя')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email address')),
                ('age', models.IntegerField(verbose_name='Возраст')),
                ('planet', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rectuit_planet', to='sith.Planet', verbose_name='Планета обитания')),
            ],
            options={
                'verbose_name': 'Рекрут',
                'verbose_name_plural': 'Рекруты',
                'db_table': 'Рекруты',
                'ordering': ['planet'],
            },
        ),
    ]
